apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres #Name of the deployments
spec:
  replicas: 1 #Number of created pods
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres #label to set in the pods
    spec:
      containers:
      - name: postgres
        image: postgres:12-alpine
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "64Mi"
        env:
        - name: POSTGRES_PASSWORD
          value: pgpass
        - name: POSTGRES_USER
          value: pguser
        - name: POSTGRES_DB
          value: pgdb
        ports:
        - containerPort: 5432 #Expose containerport to the pod
        livenessProbe: #Check that pod is ready
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30 #start checking after 30 seconds
          periodSeconds: 30 #check every 30 seconds
        readinessProbe: #Check that pod is healthy
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 3 #check every 3 seconds